# Generated by Django 5.1.6 on 2025-02-16 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
